### ISSUE TITLE
Prerender fails

### ISSUE THREAD

**Issue by felipemrodrigues** [form-data/isomorphic-form-data#2]
I'm working on a project that used to import form-data package, but now I have to enable prerender and the prerender fails. I tried to move for isomorphic-form-data but the problema also occurs.

I don't need to use form-data. I just import and it crashes.

I noted that you're using form-data. It may be the problem.

Can you help me?

**Comment by DylanPiercey** [comment]
Can you provide a stack trace or otherwise reproduce the issue?

**Comment by DylanPiercey** [comment]
Feel free to ping me with more info.
